### ISSUE TITLE
[Bug] [Qwen-image-edit-2509]There is enough memory but it still reports an error: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by kemanfufu** [nunchaku-tech/nunchaku#724]
### Checklist

- [x] 1. I have searched for related issues and FAQs (https://nunchaku.tech/docs/nunchaku/faq/faq.html) but was unable to find a solution.
- [x] 2. The issue persists in the latest version.
- [ ] 3. Please note that without environment information and a minimal reproducible example, it will be difficult for us to reproduce and address the issue, which may delay our response.
- [x] 4. If your report is a question rather than a bug, please submit it as a discussion at https://github.com/mit-han-lab/nunchaku/discussions/new/choose. Otherwise, this issue will be closed.
- [ ] 5. If this is related to ComfyUI, please report it at https://github.com/mit-han-lab/ComfyUI-nunchaku/issues.
- [x] 6. I will do my best to describe the issue in English.

### Describe the Bug

<img width="2553" height="1120" alt="Image" src="https://github.com/user-attachments/assets/c4dd885c-6d7e-4530-a1f9-689d74b4e7ad" />

<img width="2559" height="1381" alt="Image" src="https://github.com/user-attachments/assets/9b9b93e5-711c-48be-81ad-abe45cea340a" />

<img width="2254" height="1199" alt="Image" src="https://github.com/user-attachments/assets/14cd9990-e595-4d18-87f2-3826cde1c34d" />

<img width="2256" height="1195" alt="Image" src="https://github.com/user-attachments/assets/5d70d2cb-5815-4cf6-98aa-bdeba291ef56" />

Workflow:

[test-nunchaku-qwen-image-edit-2509.json](https://github.com/user-attachments/files/22523913/test-nunchaku-qwen-image-edit-2509.json)

Detailed log:

[Diagnostics-1758752682.log](https://github.com/user-attachments/files/22523918/Diagnostics-1758752682.log)

### Environment

Win10, Python 3.12.10, PyTorch 2.7.0, CUDA 12.8

### Reproduction Steps

It will definitely be reproduced under the configuration of the above workflow parameters.

**Comment by kemanfufu** [comment]
need help

**Comment by wallen0322** [comment]
> 需要帮助

把共享显存关了试试呢

**Comment by wallen0322** [comment]
> 需要帮助

显存优化改为不优化，由comfyui决定，你的这个问题跟双截棍好像没啥关系

**Comment by kemanfufu** [comment]
太感谢了，做以下调整后问题解决：
显存优化：从标准优化改为由comfyui决定
关闭共享显存
